"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.metadata = void 0;
require("./globals.css");
var google_1 = require("next/font/google");
var nav_1 = require("../components/nav");
var frame_1 = require("@/components/frame");
var navItems = [
    {
        href: "/",
        text: "Home (recent photos)",
    },
    {
        href: "/top-photos",
        text: "Top photos",
    },
    {
        href: "/best-photo",
        text: "Best photo",
    },
    {
        href: "/photo?id=123",
        text: "Photo #123",
    },
];
var inter = (0, google_1.Inter)({ subsets: ["latin"] });
exports.metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
function RootLayout(_a) {
    var children = _a.children;
    return (<html lang="en">
      <body className={inter.className}>
        <frame_1.Frame borderClassName="border-green-200 m-4" textClassName="text-green-400" text="app/layout.tsx">
          <nav_1.NavItems navItems={navItems}/>
          <frame_1.Frame borderClassName="border-green-200" textClassName="text-green-400" text="{children}" type="slot">
            {children}
          </frame_1.Frame>
        </frame_1.Frame>
      </body>
    </html>);
}
exports.default = RootLayout;
